### ISSUE TITLE
Wrong Product Weight Added in order details

### ISSUE THREAD

**Issue by vipulmishra341** [CodistoConnect/CodistoConnect-Magento2#39]
We are getting wrong order weight in Magento 2 after Sync order from eBay to Magento2 using Codisto module. The order weight is calculated with the Item total and added 1 Kg for each product so total order weight is product number * 1kg .  Suppose we have total 5 products in order then the weight for the order is 5kg. I think the issue with in the calculation at _translateWeight function., Please check and resolve it.

If we placed the order in magento 2 then the order wieght is caluated correctly but not with the Codisto module.

**Comment by lamery** [comment]
Hi vipulmishra341

The weight being imported is based a setting within Codisto.

You can see from the _translateWeight function - we are converting based on units passed.

https://github.com/CodistoConnect/CodistoConnect-Magento2/blob/6083d4efec531d313078e91c032eeefde841081d/Controller/Index/Index.php#L438

As Magento2 doesn't actually record what units the weights are entered into the system, we need to translate the weight values coming from eBay or Amazon based a setting inside Codisto:

![image](https://user-images.githubusercontent.com/253658/33314284-48517ffc-d481-11e7-8949-2a0e1c1ec8ea.png)

if you require assistance with configuration of Codisto please email support@codisto.com
