### ISSUE TITLE
after installing then module on magento 2.3.0 infinite loop

### ISSUE THREAD

**Issue by chisan0501** [CodistoConnect/CodistoConnect-Magento2#53]
I am experiencing a infinite loop at the codisto module setting page after installing version 1.91.30 and version dev-master 

I have tested with both Chrome and Microsoft Edge
tried rebuilding the static page and re-compile 

still no luck

**Comment by jlivas** [comment]
Hi Chisan,
Please reach out to our team at support@codisto.com with this issue and we will help you through to a resolution.
