### ISSUE TITLE
Customer names with special characters fail validation

### ISSUE THREAD

**Issue by GamesmenJordan** [CodistoConnect/CodistoConnect-Magento2#86]
Orders with customer names that have special characters are not filtered and fail Magento's input validation, preventing the order from being imported. Customer names are limited to letters (including international characters), spaces, hyphens, underscores and apostrophes.

**Comment by jlivas** [comment]
fixed in https://github.com/CodistoConnect/CodistoConnect-Magento2/releases/tag/1.91.48
